// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/data/repositories/goal_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/data_sources/local/dao/goal_dao.dart' as _i3;
import 'package:myassistant/data/models/enums/priority.dart' as _i6;
import 'package:myassistant/data/models/enums/status.dart' as _i5;
import 'package:myassistant/data/models/goal_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoalModel_0 extends _i1.SmartFake implements _i2.GoalModel {
  _FakeGoalModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoalDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalDao extends _i1.Mock implements _i3.GoalDao {
  MockGoalDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GoalModel> insertGoal(_i2.GoalModel? goal) =>
      (super.noSuchMethod(
            Invocation.method(#insertGoal, [goal]),
            returnValue: _i4.Future<_i2.GoalModel>.value(
              _FakeGoalModel_0(this, Invocation.method(#insertGoal, [goal])),
            ),
          )
          as _i4.Future<_i2.GoalModel>);

  @override
  _i4.Future<_i2.GoalModel?> getGoalById(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalById, [goalId]),
            returnValue: _i4.Future<_i2.GoalModel?>.value(),
          )
          as _i4.Future<_i2.GoalModel?>);

  @override
  _i4.Future<_i2.GoalModel?> getGoalByUserAndTitle(
    String? userId,
    String? title,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalByUserAndTitle, [userId, title]),
            returnValue: _i4.Future<_i2.GoalModel?>.value(),
          )
          as _i4.Future<_i2.GoalModel?>);

  @override
  _i4.Future<List<_i2.GoalModel>> getUserGoals(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserGoals, [userId]),
            returnValue: _i4.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i4.Future<List<_i2.GoalModel>>);

  @override
  _i4.Future<List<_i2.GoalModel>> getActiveGoals(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveGoals, [userId]),
            returnValue: _i4.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i4.Future<List<_i2.GoalModel>>);

  @override
  _i4.Future<List<_i2.GoalModel>> getGoalsByStatus(
    String? userId,
    _i5.GoalStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByStatus, [userId, status]),
            returnValue: _i4.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i4.Future<List<_i2.GoalModel>>);

  @override
  _i4.Future<List<_i2.GoalModel>> getGoalsByPriority(
    String? userId,
    _i6.Priority? priority,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByPriority, [userId, priority]),
            returnValue: _i4.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i4.Future<List<_i2.GoalModel>>);

  @override
  _i4.Future<List<_i2.GoalModel>> getGoalsByTags(
    String? userId,
    List<String>? tags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByTags, [userId, tags]),
            returnValue: _i4.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i4.Future<List<_i2.GoalModel>>);

  @override
  _i4.Future<List<_i2.GoalModel>> getUpcomingDeadlineGoals(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUpcomingDeadlineGoals,
              [userId],
              {#days: days},
            ),
            returnValue: _i4.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i4.Future<List<_i2.GoalModel>>);

  @override
  _i4.Future<int> updateGoal(_i2.GoalModel? goal) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoal, [goal]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateGoalStatus(String? goalId, _i5.GoalStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoalStatus, [goalId, status]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGoal, [goalId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> restoreGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreGoal, [goalId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<double> getGoalProgress(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalProgress, [goalId]),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<Map<String, dynamic>> getGoalStatistics(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalStatistics, [goalId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i2.GoalModel>> searchGoals(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchGoals, [userId, query]),
            returnValue: _i4.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i4.Future<List<_i2.GoalModel>>);

  @override
  _i4.Future<List<_i2.GoalModel>> getDeletedGoals(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedGoals, [userId]),
            returnValue: _i4.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i4.Future<List<_i2.GoalModel>>);
}
