// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/data/repositories/task_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/data_sources/local/dao/plan_dao.dart' as _i7;
import 'package:myassistant/data/data_sources/local/dao/task_dao.dart' as _i4;
import 'package:myassistant/data/models/enums/status.dart' as _i6;
import 'package:myassistant/data/models/plan_model.dart' as _i3;
import 'package:myassistant/data/models/task_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlanModel_1 extends _i1.SmartFake implements _i3.PlanModel {
  _FakePlanModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskDao extends _i1.Mock implements _i4.TaskDao {
  MockTaskDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.TaskModel> insertTask(_i2.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#insertTask, [task]),
            returnValue: _i5.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(this, Invocation.method(#insertTask, [task])),
            ),
          )
          as _i5.Future<_i2.TaskModel>);

  @override
  _i5.Future<_i2.TaskModel?> getTaskById(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [taskId]),
            returnValue: _i5.Future<_i2.TaskModel?>.value(),
          )
          as _i5.Future<_i2.TaskModel?>);

  @override
  _i5.Future<List<_i2.TaskModel>> getUserTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTasks, [userId]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> getPlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanTasks, [planId]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> getActiveTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTasks, [userId]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> getTasksInCurrentWindow(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksInCurrentWindow, [userId]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> getTasksByStatus(
    String? userId,
    _i6.TaskStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [userId, status]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> getTasksByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> getTodayTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayTasks, [userId]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> getUpcomingTasks(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingTasks, [userId], {#days: days}),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> getFutureTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFutureTasks, [userId]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> getOverdueTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, [userId]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<_i2.TaskModel?> completeTask({
    required String? taskId,
    int? actualDurationMinutes,
    String? evaluationResult,
    String? executionNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [], {
              #taskId: taskId,
              #actualDurationMinutes: actualDurationMinutes,
              #evaluationResult: evaluationResult,
              #executionNote: executionNote,
            }),
            returnValue: _i5.Future<_i2.TaskModel?>.value(),
          )
          as _i5.Future<_i2.TaskModel?>);

  @override
  _i5.Future<_i2.TaskModel?> skipTask({
    required String? taskId,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#skipTask, [], {
              #taskId: taskId,
              #reason: reason,
            }),
            returnValue: _i5.Future<_i2.TaskModel?>.value(),
          )
          as _i5.Future<_i2.TaskModel?>);

  @override
  _i5.Future<int> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i2.TaskModel?> updateTaskProgress(
    String? taskId,
    int? currentCount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskProgress, [taskId, currentCount]),
            returnValue: _i5.Future<_i2.TaskModel?>.value(),
          )
          as _i5.Future<_i2.TaskModel?>);

  @override
  _i5.Future<_i2.TaskModel?> updateTaskStatus(
    String? taskId,
    _i6.TaskStatus? newStatus, {
    bool? clearExecutionData = false,
    bool? clearSkipData = false,
    bool? clearDeletedAt = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTaskStatus,
              [taskId, newStatus],
              {
                #clearExecutionData: clearExecutionData,
                #clearSkipData: clearSkipData,
                #clearDeletedAt: clearDeletedAt,
              },
            ),
            returnValue: _i5.Future<_i2.TaskModel?>.value(),
          )
          as _i5.Future<_i2.TaskModel?>);

  @override
  _i5.Future<Map<String, dynamic>> getTaskStatistics(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskStatistics, [userId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getDailyTaskStatistics(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyTaskStatistics, [userId, date]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<double> getTaskCompletionRate(String? userId, {int? days = 30}) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskCompletionRate, [userId], {#days: days}),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<_i2.TaskModel?> getActivePlanTask(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePlanTask, [planId]),
            returnValue: _i5.Future<_i2.TaskModel?>.value(),
          )
          as _i5.Future<_i2.TaskModel?>);

  @override
  _i5.Future<List<_i2.TaskModel>> batchCreateTasks(
    List<_i2.TaskModel>? tasks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchCreateTasks, [tasks]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<_i2.TaskModel>> searchTasks(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTasks, [userId, query]),
            returnValue: _i5.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i5.Future<List<_i2.TaskModel>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getTaskHistory(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskHistory, [taskId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [PlanDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanDao extends _i1.Mock implements _i7.PlanDao {
  MockPlanDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.PlanModel> insertPlan(_i3.PlanModel? plan) =>
      (super.noSuchMethod(
            Invocation.method(#insertPlan, [plan]),
            returnValue: _i5.Future<_i3.PlanModel>.value(
              _FakePlanModel_1(this, Invocation.method(#insertPlan, [plan])),
            ),
          )
          as _i5.Future<_i3.PlanModel>);

  @override
  _i5.Future<_i3.PlanModel?> getPlanById(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanById, [planId]),
            returnValue: _i5.Future<_i3.PlanModel?>.value(),
          )
          as _i5.Future<_i3.PlanModel?>);

  @override
  _i5.Future<List<_i3.PlanModel>> getUserPlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPlans, [userId]),
            returnValue: _i5.Future<List<_i3.PlanModel>>.value(
              <_i3.PlanModel>[],
            ),
          )
          as _i5.Future<List<_i3.PlanModel>>);

  @override
  _i5.Future<List<_i3.PlanModel>> getGoalPlans(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalPlans, [goalId]),
            returnValue: _i5.Future<List<_i3.PlanModel>>.value(
              <_i3.PlanModel>[],
            ),
          )
          as _i5.Future<List<_i3.PlanModel>>);

  @override
  _i5.Future<List<_i3.PlanModel>> getActivePlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePlans, [userId]),
            returnValue: _i5.Future<List<_i3.PlanModel>>.value(
              <_i3.PlanModel>[],
            ),
          )
          as _i5.Future<List<_i3.PlanModel>>);

  @override
  _i5.Future<List<_i3.PlanModel>> getPlansByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i5.Future<List<_i3.PlanModel>>.value(
              <_i3.PlanModel>[],
            ),
          )
          as _i5.Future<List<_i3.PlanModel>>);

  @override
  _i5.Future<int> updatePlan(_i3.PlanModel? plan) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlan, [plan]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deletePlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlan, [planId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> restorePlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#restorePlan, [planId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> isPlanNameExists(String? userId, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#isPlanNameExists, [userId, name]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.PlanModel?> getPlanByUserAndName(
    String? userId,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanByUserAndName, [userId, name]),
            returnValue: _i5.Future<_i3.PlanModel?>.value(),
          )
          as _i5.Future<_i3.PlanModel?>);

  @override
  _i5.Future<Map<String, dynamic>> getPlanStatistics(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanStatistics, [planId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<int> updatePlanStatistics({
    required String? planId,
    int? totalTaskCount,
    int? completedTaskCount,
    int? skippedTaskCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlanStatistics, [], {
              #planId: planId,
              #totalTaskCount: totalTaskCount,
              #completedTaskCount: completedTaskCount,
              #skippedTaskCount: skippedTaskCount,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<double> calculateCompletionRate(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#calculateCompletionRate, [planId]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<List<_i3.PlanModel>> getPlansNeedingTaskGeneration(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansNeedingTaskGeneration, [userId]),
            returnValue: _i5.Future<List<_i3.PlanModel>>.value(
              <_i3.PlanModel>[],
            ),
          )
          as _i5.Future<List<_i3.PlanModel>>);

  @override
  _i5.Future<List<_i3.PlanModel>> searchPlans(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPlans, [userId, query]),
            returnValue: _i5.Future<List<_i3.PlanModel>>.value(
              <_i3.PlanModel>[],
            ),
          )
          as _i5.Future<List<_i3.PlanModel>>);

  @override
  _i5.Future<List<_i3.PlanModel>> getDeletedPlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedPlans, [userId]),
            returnValue: _i5.Future<List<_i3.PlanModel>>.value(
              <_i3.PlanModel>[],
            ),
          )
          as _i5.Future<List<_i3.PlanModel>>);

  @override
  _i5.Future<List<_i3.PlanModel>> getPlansEndingSoon(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansEndingSoon, [userId], {#days: days}),
            returnValue: _i5.Future<List<_i3.PlanModel>>.value(
              <_i3.PlanModel>[],
            ),
          )
          as _i5.Future<List<_i3.PlanModel>>);
}
