// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/data/services/authentication_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/user_model.dart' as _i2;
import 'package:myassistant/data/models/user_settings_model.dart' as _i3;
import 'package:myassistant/domain/repositories/i_user_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserSettingsModel_1 extends _i1.SmartFake
    implements _i3.UserSettingsModel {
  _FakeUserSettingsModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i4.IUserRepository {
  MockIUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserModel> createUser({
    required String? username,
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #username: username,
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i5.Future<_i2.UserModel>.value(
              _FakeUserModel_0(
                this,
                Invocation.method(#createUser, [], {
                  #username: username,
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserModel>);

  @override
  _i5.Future<_i2.UserModel?> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i5.Future<_i2.UserModel?>.value(),
          )
          as _i5.Future<_i2.UserModel?>);

  @override
  _i5.Future<_i2.UserModel?> getUserByUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUsername, [username]),
            returnValue: _i5.Future<_i2.UserModel?>.value(),
          )
          as _i5.Future<_i2.UserModel?>);

  @override
  _i5.Future<_i2.UserModel?> getUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue: _i5.Future<_i2.UserModel?>.value(),
          )
          as _i5.Future<_i2.UserModel?>);

  @override
  _i5.Future<_i2.UserModel?> authenticate(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [username, password]),
            returnValue: _i5.Future<_i2.UserModel?>.value(),
          )
          as _i5.Future<_i2.UserModel?>);

  @override
  _i5.Future<_i2.UserModel> updateUser(_i2.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i5.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#updateUser, [user])),
            ),
          )
          as _i5.Future<_i2.UserModel>);

  @override
  _i5.Future<bool> updatePassword(
    String? userId,
    String? oldPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [
              userId,
              oldPassword,
              newPassword,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.UserSettingsModel?> getUserSettings(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserSettings, [userId]),
            returnValue: _i5.Future<_i3.UserSettingsModel?>.value(),
          )
          as _i5.Future<_i3.UserSettingsModel?>);

  @override
  _i5.Future<_i3.UserSettingsModel> updateUserSettings(
    _i3.UserSettingsModel? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserSettings, [settings]),
            returnValue: _i5.Future<_i3.UserSettingsModel>.value(
              _FakeUserSettingsModel_1(
                this,
                Invocation.method(#updateUserSettings, [settings]),
              ),
            ),
          )
          as _i5.Future<_i3.UserSettingsModel>);

  @override
  _i5.Future<_i3.UserSettingsModel> createDefaultSettings(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#createDefaultSettings, [userId]),
            returnValue: _i5.Future<_i3.UserSettingsModel>.value(
              _FakeUserSettingsModel_1(
                this,
                Invocation.method(#createDefaultSettings, [userId]),
              ),
            ),
          )
          as _i5.Future<_i3.UserSettingsModel>);

  @override
  _i5.Future<Map<String, dynamic>> getUserStatistics(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatistics, [userId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isUsernameExists(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#isUsernameExists, [username]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isEmailExists(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#isEmailExists, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
