// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/data/services/plan_management_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/enums/priority.dart' as _i8;
import 'package:myassistant/data/models/enums/status.dart' as _i9;
import 'package:myassistant/data/models/goal_model.dart' as _i3;
import 'package:myassistant/data/models/plan_model.dart' as _i2;
import 'package:myassistant/data/models/task_model.dart' as _i4;
import 'package:myassistant/data/services/task_generation_service.dart' as _i11;
import 'package:myassistant/domain/repositories/i_goal_repository.dart' as _i7;
import 'package:myassistant/domain/repositories/i_plan_repository.dart' as _i5;
import 'package:myassistant/domain/repositories/i_task_repository.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlanModel_0 extends _i1.SmartFake implements _i2.PlanModel {
  _FakePlanModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoalModel_1 extends _i1.SmartFake implements _i3.GoalModel {
  _FakeGoalModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskModel_2 extends _i1.SmartFake implements _i4.TaskModel {
  _FakeTaskModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IPlanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPlanRepository extends _i1.Mock implements _i5.IPlanRepository {
  MockIPlanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.PlanModel> createPlan({
    required String? userId,
    required String? goalId,
    required String? name,
    String? description,
    required DateTime? startDate,
    required DateTime? endDate,
    required _i2.RepeatRule? repeatRule,
    required _i2.TaskConfiguration? taskConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPlan, [], {
              #userId: userId,
              #goalId: goalId,
              #name: name,
              #description: description,
              #startDate: startDate,
              #endDate: endDate,
              #repeatRule: repeatRule,
              #taskConfig: taskConfig,
            }),
            returnValue: _i6.Future<_i2.PlanModel>.value(
              _FakePlanModel_0(
                this,
                Invocation.method(#createPlan, [], {
                  #userId: userId,
                  #goalId: goalId,
                  #name: name,
                  #description: description,
                  #startDate: startDate,
                  #endDate: endDate,
                  #repeatRule: repeatRule,
                  #taskConfig: taskConfig,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.PlanModel>);

  @override
  _i6.Future<_i2.PlanModel?> getPlanById(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanById, [planId]),
            returnValue: _i6.Future<_i2.PlanModel?>.value(),
          )
          as _i6.Future<_i2.PlanModel?>);

  @override
  _i6.Future<List<_i2.PlanModel>> getUserPlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPlans, [userId]),
            returnValue: _i6.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i6.Future<List<_i2.PlanModel>>);

  @override
  _i6.Future<List<_i2.PlanModel>> getGoalPlans(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalPlans, [goalId]),
            returnValue: _i6.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i6.Future<List<_i2.PlanModel>>);

  @override
  _i6.Future<List<_i2.PlanModel>> getActivePlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePlans, [userId]),
            returnValue: _i6.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i6.Future<List<_i2.PlanModel>>);

  @override
  _i6.Future<List<_i2.PlanModel>> getPlansByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i6.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i6.Future<List<_i2.PlanModel>>);

  @override
  _i6.Future<_i2.PlanModel> updatePlan(_i2.PlanModel? plan) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlan, [plan]),
            returnValue: _i6.Future<_i2.PlanModel>.value(
              _FakePlanModel_0(this, Invocation.method(#updatePlan, [plan])),
            ),
          )
          as _i6.Future<_i2.PlanModel>);

  @override
  _i6.Future<bool> deletePlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlan, [planId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> restorePlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#restorePlan, [planId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isPlanNameExists(String? userId, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#isPlanNameExists, [userId, name]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.PlanModel?> getPlanByUserAndName(
    String? userId,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanByUserAndName, [userId, name]),
            returnValue: _i6.Future<_i2.PlanModel?>.value(),
          )
          as _i6.Future<_i2.PlanModel?>);

  @override
  _i6.Future<Map<String, dynamic>> getPlanStatistics(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanStatistics, [planId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> updatePlanStatistics({
    required String? planId,
    int? totalTaskCount,
    int? completedTaskCount,
    int? skippedTaskCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlanStatistics, [], {
              #planId: planId,
              #totalTaskCount: totalTaskCount,
              #completedTaskCount: completedTaskCount,
              #skippedTaskCount: skippedTaskCount,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<double> calculateCompletionRate(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#calculateCompletionRate, [planId]),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<List<_i2.PlanModel>> getPlansNeedingTaskGeneration(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansNeedingTaskGeneration, [userId]),
            returnValue: _i6.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i6.Future<List<_i2.PlanModel>>);

  @override
  _i6.Future<List<_i2.PlanModel>> searchPlans(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPlans, [userId, query]),
            returnValue: _i6.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i6.Future<List<_i2.PlanModel>>);

  @override
  _i6.Future<List<_i2.PlanModel>> getDeletedPlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedPlans, [userId]),
            returnValue: _i6.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i6.Future<List<_i2.PlanModel>>);

  @override
  _i6.Future<List<_i2.PlanModel>> getPlansEndingSoon(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansEndingSoon, [userId], {#days: days}),
            returnValue: _i6.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i6.Future<List<_i2.PlanModel>>);
}

/// A class which mocks [IGoalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGoalRepository extends _i1.Mock implements _i7.IGoalRepository {
  MockIGoalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.GoalModel> createGoal({
    required String? userId,
    required String? title,
    String? description,
    List<String>? tags,
    DateTime? deadline,
    _i8.Priority? priority = _i8.Priority.medium,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGoal, [], {
              #userId: userId,
              #title: title,
              #description: description,
              #tags: tags,
              #deadline: deadline,
              #priority: priority,
              #successCriteria: successCriteria,
            }),
            returnValue: _i6.Future<_i3.GoalModel>.value(
              _FakeGoalModel_1(
                this,
                Invocation.method(#createGoal, [], {
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #tags: tags,
                  #deadline: deadline,
                  #priority: priority,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.GoalModel>);

  @override
  _i6.Future<_i3.GoalModel?> getGoalById(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalById, [goalId]),
            returnValue: _i6.Future<_i3.GoalModel?>.value(),
          )
          as _i6.Future<_i3.GoalModel?>);

  @override
  _i6.Future<_i3.GoalModel?> getGoalByUserAndTitle(
    String? userId,
    String? title,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalByUserAndTitle, [userId, title]),
            returnValue: _i6.Future<_i3.GoalModel?>.value(),
          )
          as _i6.Future<_i3.GoalModel?>);

  @override
  _i6.Future<List<_i3.GoalModel>> getUserGoals(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserGoals, [userId]),
            returnValue: _i6.Future<List<_i3.GoalModel>>.value(
              <_i3.GoalModel>[],
            ),
          )
          as _i6.Future<List<_i3.GoalModel>>);

  @override
  _i6.Future<List<_i3.GoalModel>> getActiveGoals(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveGoals, [userId]),
            returnValue: _i6.Future<List<_i3.GoalModel>>.value(
              <_i3.GoalModel>[],
            ),
          )
          as _i6.Future<List<_i3.GoalModel>>);

  @override
  _i6.Future<List<_i3.GoalModel>> getGoalsByStatus(
    String? userId,
    _i9.GoalStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByStatus, [userId, status]),
            returnValue: _i6.Future<List<_i3.GoalModel>>.value(
              <_i3.GoalModel>[],
            ),
          )
          as _i6.Future<List<_i3.GoalModel>>);

  @override
  _i6.Future<List<_i3.GoalModel>> getGoalsByPriority(
    String? userId,
    _i8.Priority? priority,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByPriority, [userId, priority]),
            returnValue: _i6.Future<List<_i3.GoalModel>>.value(
              <_i3.GoalModel>[],
            ),
          )
          as _i6.Future<List<_i3.GoalModel>>);

  @override
  _i6.Future<List<_i3.GoalModel>> getGoalsByTags(
    String? userId,
    List<String>? tags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByTags, [userId, tags]),
            returnValue: _i6.Future<List<_i3.GoalModel>>.value(
              <_i3.GoalModel>[],
            ),
          )
          as _i6.Future<List<_i3.GoalModel>>);

  @override
  _i6.Future<List<_i3.GoalModel>> getUpcomingDeadlineGoals(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUpcomingDeadlineGoals,
              [userId],
              {#days: days},
            ),
            returnValue: _i6.Future<List<_i3.GoalModel>>.value(
              <_i3.GoalModel>[],
            ),
          )
          as _i6.Future<List<_i3.GoalModel>>);

  @override
  _i6.Future<_i3.GoalModel> updateGoal(_i3.GoalModel? goal) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoal, [goal]),
            returnValue: _i6.Future<_i3.GoalModel>.value(
              _FakeGoalModel_1(this, Invocation.method(#updateGoal, [goal])),
            ),
          )
          as _i6.Future<_i3.GoalModel>);

  @override
  _i6.Future<_i3.GoalModel> updateGoalStatus(
    String? goalId,
    _i9.GoalStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoalStatus, [goalId, status]),
            returnValue: _i6.Future<_i3.GoalModel>.value(
              _FakeGoalModel_1(
                this,
                Invocation.method(#updateGoalStatus, [goalId, status]),
              ),
            ),
          )
          as _i6.Future<_i3.GoalModel>);

  @override
  _i6.Future<bool> deleteGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGoal, [goalId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> restoreGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreGoal, [goalId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<double> getGoalProgress(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalProgress, [goalId]),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<Map<String, dynamic>> getGoalStatistics(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalStatistics, [goalId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> addPlanToGoal(String? goalId, String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#addPlanToGoal, [goalId, planId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> removePlanFromGoal(String? goalId, String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#removePlanFromGoal, [goalId, planId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i3.GoalModel>> searchGoals(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchGoals, [userId, query]),
            returnValue: _i6.Future<List<_i3.GoalModel>>.value(
              <_i3.GoalModel>[],
            ),
          )
          as _i6.Future<List<_i3.GoalModel>>);

  @override
  _i6.Future<List<_i3.GoalModel>> getDeletedGoals(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedGoals, [userId]),
            returnValue: _i6.Future<List<_i3.GoalModel>>.value(
              <_i3.GoalModel>[],
            ),
          )
          as _i6.Future<List<_i3.GoalModel>>);
}

/// A class which mocks [ITaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRepository extends _i1.Mock implements _i10.ITaskRepository {
  MockITaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.TaskModel> createTask({
    required String? userId,
    required String? planId,
    required String? name,
    String? description,
    required _i2.TaskConfiguration? config,
    required DateTime? windowStartTime,
    required DateTime? windowEndTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {
              #userId: userId,
              #planId: planId,
              #name: name,
              #description: description,
              #config: config,
              #windowStartTime: windowStartTime,
              #windowEndTime: windowEndTime,
            }),
            returnValue: _i6.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#createTask, [], {
                  #userId: userId,
                  #planId: planId,
                  #name: name,
                  #description: description,
                  #config: config,
                  #windowStartTime: windowStartTime,
                  #windowEndTime: windowEndTime,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.TaskModel>);

  @override
  _i6.Future<_i4.TaskModel?> getTaskById(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [taskId]),
            returnValue: _i6.Future<_i4.TaskModel?>.value(),
          )
          as _i6.Future<_i4.TaskModel?>);

  @override
  _i6.Future<List<_i4.TaskModel>> getUserTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTasks, [userId]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> getPlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanTasks, [planId]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> getActiveTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTasks, [userId]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> getTasksInCurrentWindow(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksInCurrentWindow, [userId]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> getTasksByStatus(
    String? userId,
    _i9.TaskStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [userId, status]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> getTasksByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> getTodayTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayTasks, [userId]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> getUpcomingTasks(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingTasks, [userId], {#days: days}),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> getFutureTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFutureTasks, [userId]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> getOverdueTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, [userId]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<_i4.TaskModel> completeTask({
    required String? taskId,
    int? actualDurationMinutes,
    String? evaluationResult,
    String? executionNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [], {
              #taskId: taskId,
              #actualDurationMinutes: actualDurationMinutes,
              #evaluationResult: evaluationResult,
              #executionNote: executionNote,
            }),
            returnValue: _i6.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#completeTask, [], {
                  #taskId: taskId,
                  #actualDurationMinutes: actualDurationMinutes,
                  #evaluationResult: evaluationResult,
                  #executionNote: executionNote,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.TaskModel>);

  @override
  _i6.Future<_i4.TaskModel> skipTask({
    required String? taskId,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#skipTask, [], {
              #taskId: taskId,
              #reason: reason,
            }),
            returnValue: _i6.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#skipTask, [], {
                  #taskId: taskId,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.TaskModel>);

  @override
  _i6.Future<_i4.TaskModel> updateTaskProgress(
    String? taskId,
    int? currentCount, {
    int? actualDurationMinutes,
    String? evaluationResult,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTaskProgress,
              [taskId, currentCount],
              {
                #actualDurationMinutes: actualDurationMinutes,
                #evaluationResult: evaluationResult,
              },
            ),
            returnValue: _i6.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(
                  #updateTaskProgress,
                  [taskId, currentCount],
                  {
                    #actualDurationMinutes: actualDurationMinutes,
                    #evaluationResult: evaluationResult,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.TaskModel>);

  @override
  _i6.Future<_i4.TaskModel> updateTaskStatus({
    required String? taskId,
    required _i9.TaskStatus? status,
    bool? clearExecutionData = false,
    bool? clearSkipData = false,
    bool? clearDeletedAt = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [], {
              #taskId: taskId,
              #status: status,
              #clearExecutionData: clearExecutionData,
              #clearSkipData: clearSkipData,
              #clearDeletedAt: clearDeletedAt,
            }),
            returnValue: _i6.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#updateTaskStatus, [], {
                  #taskId: taskId,
                  #status: status,
                  #clearExecutionData: clearExecutionData,
                  #clearSkipData: clearSkipData,
                  #clearDeletedAt: clearDeletedAt,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.TaskModel>);

  @override
  _i6.Future<Map<String, dynamic>> getTaskStatistics(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskStatistics, [userId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getDailyTaskStatistics(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyTaskStatistics, [userId, date]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<double> getTaskCompletionRate(String? userId, {int? days = 30}) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskCompletionRate, [userId], {#days: days}),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<_i4.TaskModel?> getActivePlanTask(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePlanTask, [planId]),
            returnValue: _i6.Future<_i4.TaskModel?>.value(),
          )
          as _i6.Future<_i4.TaskModel?>);

  @override
  _i6.Future<List<_i4.TaskModel>> batchCreateTasks(
    List<_i4.TaskModel>? tasks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchCreateTasks, [tasks]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> searchTasks(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTasks, [userId, query]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getTaskHistory(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskHistory, [taskId]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<bool> addTaskHistoryEntry({
    required String? taskId,
    required String? userId,
    required String? action,
    String? oldStatus,
    String? newStatus,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskHistoryEntry, [], {
              #taskId: taskId,
              #userId: userId,
              #action: action,
              #oldStatus: oldStatus,
              #newStatus: newStatus,
              #metadata: metadata,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> deletePlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlanTasks, [planId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [TaskGenerationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskGenerationService extends _i1.Mock
    implements _i11.TaskGenerationService {
  MockTaskGenerationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.TaskModel?> generateNextTask(_i2.PlanModel? plan) =>
      (super.noSuchMethod(
            Invocation.method(#generateNextTask, [plan]),
            returnValue: _i6.Future<_i4.TaskModel?>.value(),
          )
          as _i6.Future<_i4.TaskModel?>);

  @override
  _i6.Future<List<_i4.TaskModel>> generateAllPendingTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#generateAllPendingTasks, [userId]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);

  @override
  _i6.Future<List<_i4.TaskModel>> generateTasksForDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateTasksForDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i6.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i4.TaskModel>>);
}
