// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/data/services/task_execution_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/enums/status.dart' as _i6;
import 'package:myassistant/data/models/plan_model.dart' as _i5;
import 'package:myassistant/data/models/task_model.dart' as _i2;
import 'package:myassistant/domain/repositories/i_task_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ITaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRepository extends _i1.Mock implements _i3.ITaskRepository {
  MockITaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TaskModel> createTask({
    required String? userId,
    required String? planId,
    required String? name,
    String? description,
    required _i5.TaskConfiguration? config,
    required DateTime? windowStartTime,
    required DateTime? windowEndTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {
              #userId: userId,
              #planId: planId,
              #name: name,
              #description: description,
              #config: config,
              #windowStartTime: windowStartTime,
              #windowEndTime: windowEndTime,
            }),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#createTask, [], {
                  #userId: userId,
                  #planId: planId,
                  #name: name,
                  #description: description,
                  #config: config,
                  #windowStartTime: windowStartTime,
                  #windowEndTime: windowEndTime,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<_i2.TaskModel?> getTaskById(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [taskId]),
            returnValue: _i4.Future<_i2.TaskModel?>.value(),
          )
          as _i4.Future<_i2.TaskModel?>);

  @override
  _i4.Future<List<_i2.TaskModel>> getUserTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTasks, [userId]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<_i2.TaskModel>> getPlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanTasks, [planId]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<_i2.TaskModel>> getActiveTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTasks, [userId]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<_i2.TaskModel>> getTasksInCurrentWindow(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksInCurrentWindow, [userId]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<_i2.TaskModel>> getTasksByStatus(
    String? userId,
    _i6.TaskStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [userId, status]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<_i2.TaskModel>> getTasksByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<_i2.TaskModel>> getTodayTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayTasks, [userId]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<_i2.TaskModel>> getUpcomingTasks(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingTasks, [userId], {#days: days}),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<_i2.TaskModel>> getOverdueTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, [userId]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<_i2.TaskModel> completeTask({
    required String? taskId,
    int? actualDurationMinutes,
    String? evaluationResult,
    String? executionNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [], {
              #taskId: taskId,
              #actualDurationMinutes: actualDurationMinutes,
              #evaluationResult: evaluationResult,
              #executionNote: executionNote,
            }),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#completeTask, [], {
                  #taskId: taskId,
                  #actualDurationMinutes: actualDurationMinutes,
                  #evaluationResult: evaluationResult,
                  #executionNote: executionNote,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<_i2.TaskModel> skipTask({
    required String? taskId,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#skipTask, [], {
              #taskId: taskId,
              #reason: reason,
            }),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#skipTask, [], {
                  #taskId: taskId,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<_i2.TaskModel> updateTaskProgress(
    String? taskId,
    int? currentCount, {
    int? actualDurationMinutes,
    String? evaluationResult,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTaskProgress,
              [taskId, currentCount],
              {
                #actualDurationMinutes: actualDurationMinutes,
                #evaluationResult: evaluationResult,
              },
            ),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(
                  #updateTaskProgress,
                  [taskId, currentCount],
                  {
                    #actualDurationMinutes: actualDurationMinutes,
                    #evaluationResult: evaluationResult,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<_i2.TaskModel> updateTaskStatus({
    required String? taskId,
    required _i6.TaskStatus? status,
    bool? clearExecutionData = false,
    bool? clearSkipData = false,
    bool? clearDeletedAt = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [], {
              #taskId: taskId,
              #status: status,
              #clearExecutionData: clearExecutionData,
              #clearSkipData: clearSkipData,
              #clearDeletedAt: clearDeletedAt,
            }),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#updateTaskStatus, [], {
                  #taskId: taskId,
                  #status: status,
                  #clearExecutionData: clearExecutionData,
                  #clearSkipData: clearSkipData,
                  #clearDeletedAt: clearDeletedAt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<Map<String, dynamic>> getTaskStatistics(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskStatistics, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getDailyTaskStatistics(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyTaskStatistics, [userId, date]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<double> getTaskCompletionRate(String? userId, {int? days = 30}) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskCompletionRate, [userId], {#days: days}),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<_i2.TaskModel?> getActivePlanTask(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePlanTask, [planId]),
            returnValue: _i4.Future<_i2.TaskModel?>.value(),
          )
          as _i4.Future<_i2.TaskModel?>);

  @override
  _i4.Future<List<_i2.TaskModel>> batchCreateTasks(
    List<_i2.TaskModel>? tasks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchCreateTasks, [tasks]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<_i2.TaskModel>> searchTasks(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTasks, [userId, query]),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getTaskHistory(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskHistory, [taskId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> addTaskHistoryEntry({
    required String? taskId,
    required String? userId,
    required String? action,
    String? oldStatus,
    String? newStatus,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskHistoryEntry, [], {
              #taskId: taskId,
              #userId: userId,
              #action: action,
              #oldStatus: oldStatus,
              #newStatus: newStatus,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deletePlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlanTasks, [planId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
