// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/presentation/providers/app_lifecycle_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/task_model.dart' as _i4;
import 'package:myassistant/data/services/task_refresh_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRefreshResult_0 extends _i1.SmartFake implements _i2.RefreshResult {
  _FakeRefreshResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRefreshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRefreshService extends _i1.Mock
    implements _i2.TaskRefreshService {
  MockTaskRefreshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.RefreshResult> refreshAllTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAllTasks, [userId]),
            returnValue: _i3.Future<_i2.RefreshResult>.value(
              _FakeRefreshResult_0(
                this,
                Invocation.method(#refreshAllTasks, [userId]),
              ),
            ),
          )
          as _i3.Future<_i2.RefreshResult>);

  @override
  void startPeriodicRefresh({
    required String? userId,
    Duration? interval = const Duration(hours: 1),
    dynamic Function(_i2.RefreshResult)? onRefresh,
  }) => super.noSuchMethod(
    Invocation.method(#startPeriodicRefresh, [], {
      #userId: userId,
      #interval: interval,
      #onRefresh: onRefresh,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void stopPeriodicRefresh() => super.noSuchMethod(
    Invocation.method(#stopPeriodicRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> scheduleRefreshAt(List<DateTime>? times, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleRefreshAt, [times, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.RefreshResult> refreshOnResume(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshOnResume, [userId]),
            returnValue: _i3.Future<_i2.RefreshResult>.value(
              _FakeRefreshResult_0(
                this,
                Invocation.method(#refreshOnResume, [userId]),
              ),
            ),
          )
          as _i3.Future<_i2.RefreshResult>);

  @override
  _i3.Future<_i4.TaskModel?> refreshPlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshPlanTasks, [planId]),
            returnValue: _i3.Future<_i4.TaskModel?>.value(),
          )
          as _i3.Future<_i4.TaskModel?>);

  @override
  _i3.Future<int> cleanupOldTasks({
    required String? userId,
    int? daysOld = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldTasks, [], {
              #userId: userId,
              #daysOld: daysOld,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
