// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/presentation/providers/auth_state_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/user_model.dart' as _i3;
import 'package:myassistant/data/services/authentication_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationService extends _i1.Mock
    implements _i2.AuthenticationService {
  MockAuthenticationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isSessionExpired =>
      (super.noSuchMethod(
            Invocation.getter(#isSessionExpired),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<_i2.AuthResult> signUp({
    required String? username,
    required String? password,
    required String? email,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #username: username,
              #password: password,
              #email: email,
              #displayName: displayName,
            }),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#signUp, [], {
                  #username: username,
                  #password: password,
                  #email: email,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> signIn({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#signIn, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void refreshSession() => super.noSuchMethod(
    Invocation.method(#refreshSession, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> changePassword({
    required String? userId,
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #userId: userId,
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i3.UserModel> updateProfile({
    required String? userId,
    String? displayName,
    String? email,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #userId: userId,
              #displayName: displayName,
              #email: email,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i4.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#updateProfile, [], {
                  #userId: userId,
                  #displayName: displayName,
                  #email: email,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.UserModel>);

  @override
  _i4.Future<bool> deactivateAccount({
    required String? userId,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateAccount, [], {
              #userId: userId,
              #password: password,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
