// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/presentation/providers/goal_state_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/enums/priority.dart' as _i6;
import 'package:myassistant/data/models/enums/status.dart' as _i7;
import 'package:myassistant/data/models/goal_model.dart' as _i2;
import 'package:myassistant/data/services/goal_management_service.dart' as _i3;
import 'package:myassistant/domain/repositories/i_goal_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoalModel_0 extends _i1.SmartFake implements _i2.GoalModel {
  _FakeGoalModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoalStatistics_1 extends _i1.SmartFake
    implements _i3.GoalStatistics {
  _FakeGoalStatistics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoalAchievementResult_2 extends _i1.SmartFake
    implements _i3.GoalAchievementResult {
  _FakeGoalAchievementResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IGoalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGoalRepository extends _i1.Mock implements _i4.IGoalRepository {
  MockIGoalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GoalModel> createGoal({
    required String? userId,
    required String? title,
    String? description,
    List<String>? tags,
    DateTime? deadline,
    _i6.Priority? priority = _i6.Priority.medium,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGoal, [], {
              #userId: userId,
              #title: title,
              #description: description,
              #tags: tags,
              #deadline: deadline,
              #priority: priority,
              #successCriteria: successCriteria,
            }),
            returnValue: _i5.Future<_i2.GoalModel>.value(
              _FakeGoalModel_0(
                this,
                Invocation.method(#createGoal, [], {
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #tags: tags,
                  #deadline: deadline,
                  #priority: priority,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.GoalModel>);

  @override
  _i5.Future<_i2.GoalModel?> getGoalById(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalById, [goalId]),
            returnValue: _i5.Future<_i2.GoalModel?>.value(),
          )
          as _i5.Future<_i2.GoalModel?>);

  @override
  _i5.Future<_i2.GoalModel?> getGoalByUserAndTitle(
    String? userId,
    String? title,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalByUserAndTitle, [userId, title]),
            returnValue: _i5.Future<_i2.GoalModel?>.value(),
          )
          as _i5.Future<_i2.GoalModel?>);

  @override
  _i5.Future<List<_i2.GoalModel>> getUserGoals(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserGoals, [userId]),
            returnValue: _i5.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i5.Future<List<_i2.GoalModel>>);

  @override
  _i5.Future<List<_i2.GoalModel>> getActiveGoals(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveGoals, [userId]),
            returnValue: _i5.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i5.Future<List<_i2.GoalModel>>);

  @override
  _i5.Future<List<_i2.GoalModel>> getGoalsByStatus(
    String? userId,
    _i7.GoalStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByStatus, [userId, status]),
            returnValue: _i5.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i5.Future<List<_i2.GoalModel>>);

  @override
  _i5.Future<List<_i2.GoalModel>> getGoalsByPriority(
    String? userId,
    _i6.Priority? priority,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByPriority, [userId, priority]),
            returnValue: _i5.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i5.Future<List<_i2.GoalModel>>);

  @override
  _i5.Future<List<_i2.GoalModel>> getGoalsByTags(
    String? userId,
    List<String>? tags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByTags, [userId, tags]),
            returnValue: _i5.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i5.Future<List<_i2.GoalModel>>);

  @override
  _i5.Future<List<_i2.GoalModel>> getUpcomingDeadlineGoals(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUpcomingDeadlineGoals,
              [userId],
              {#days: days},
            ),
            returnValue: _i5.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i5.Future<List<_i2.GoalModel>>);

  @override
  _i5.Future<_i2.GoalModel> updateGoal(_i2.GoalModel? goal) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoal, [goal]),
            returnValue: _i5.Future<_i2.GoalModel>.value(
              _FakeGoalModel_0(this, Invocation.method(#updateGoal, [goal])),
            ),
          )
          as _i5.Future<_i2.GoalModel>);

  @override
  _i5.Future<_i2.GoalModel> updateGoalStatus(
    String? goalId,
    _i7.GoalStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoalStatus, [goalId, status]),
            returnValue: _i5.Future<_i2.GoalModel>.value(
              _FakeGoalModel_0(
                this,
                Invocation.method(#updateGoalStatus, [goalId, status]),
              ),
            ),
          )
          as _i5.Future<_i2.GoalModel>);

  @override
  _i5.Future<bool> deleteGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGoal, [goalId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> restoreGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreGoal, [goalId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<double> getGoalProgress(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalProgress, [goalId]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<Map<String, dynamic>> getGoalStatistics(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalStatistics, [goalId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> addPlanToGoal(String? goalId, String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#addPlanToGoal, [goalId, planId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removePlanFromGoal(String? goalId, String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#removePlanFromGoal, [goalId, planId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i2.GoalModel>> searchGoals(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchGoals, [userId, query]),
            returnValue: _i5.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i5.Future<List<_i2.GoalModel>>);

  @override
  _i5.Future<List<_i2.GoalModel>> getDeletedGoals(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedGoals, [userId]),
            returnValue: _i5.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i5.Future<List<_i2.GoalModel>>);
}

/// A class which mocks [GoalManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalManagementService extends _i1.Mock
    implements _i3.GoalManagementService {
  MockGoalManagementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GoalModel> createGoal({
    required String? userId,
    required String? title,
    String? description,
    DateTime? deadline,
    _i6.Priority? priority = _i6.Priority.medium,
    List<String>? tags,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGoal, [], {
              #userId: userId,
              #title: title,
              #description: description,
              #deadline: deadline,
              #priority: priority,
              #tags: tags,
              #successCriteria: successCriteria,
            }),
            returnValue: _i5.Future<_i2.GoalModel>.value(
              _FakeGoalModel_0(
                this,
                Invocation.method(#createGoal, [], {
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #deadline: deadline,
                  #priority: priority,
                  #tags: tags,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.GoalModel>);

  @override
  _i5.Future<_i2.GoalModel> updateGoal({
    required String? goalId,
    String? title,
    String? description,
    DateTime? deadline,
    _i6.Priority? priority,
    List<String>? tags,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoal, [], {
              #goalId: goalId,
              #title: title,
              #description: description,
              #deadline: deadline,
              #priority: priority,
              #tags: tags,
              #successCriteria: successCriteria,
            }),
            returnValue: _i5.Future<_i2.GoalModel>.value(
              _FakeGoalModel_0(
                this,
                Invocation.method(#updateGoal, [], {
                  #goalId: goalId,
                  #title: title,
                  #description: description,
                  #deadline: deadline,
                  #priority: priority,
                  #tags: tags,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.GoalModel>);

  @override
  _i5.Future<bool> archiveGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#archiveGoal, [goalId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGoal, [goalId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.GoalStatistics> calculateGoalProgress(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#calculateGoalProgress, [goalId]),
            returnValue: _i5.Future<_i3.GoalStatistics>.value(
              _FakeGoalStatistics_1(
                this,
                Invocation.method(#calculateGoalProgress, [goalId]),
              ),
            ),
          )
          as _i5.Future<_i3.GoalStatistics>);

  @override
  _i5.Future<_i3.GoalAchievementResult> checkGoalAchievement(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#checkGoalAchievement, [goalId]),
            returnValue: _i5.Future<_i3.GoalAchievementResult>.value(
              _FakeGoalAchievementResult_2(
                this,
                Invocation.method(#checkGoalAchievement, [goalId]),
              ),
            ),
          )
          as _i5.Future<_i3.GoalAchievementResult>);

  @override
  _i5.Future<List<String>> getGoalRecommendations(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalRecommendations, [goalId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<Map<String, List<_i2.GoalModel>>> getGoalsByTags(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsByTags, [userId]),
            returnValue: _i5.Future<Map<String, List<_i2.GoalModel>>>.value(
              <String, List<_i2.GoalModel>>{},
            ),
          )
          as _i5.Future<Map<String, List<_i2.GoalModel>>>);

  @override
  _i5.Future<List<_i2.GoalModel>> getGoalsApproachingDeadline({
    required String? userId,
    int? daysThreshold = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsApproachingDeadline, [], {
              #userId: userId,
              #daysThreshold: daysThreshold,
            }),
            returnValue: _i5.Future<List<_i2.GoalModel>>.value(
              <_i2.GoalModel>[],
            ),
          )
          as _i5.Future<List<_i2.GoalModel>>);

  @override
  _i5.Future<_i2.GoalModel> resumeGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeGoal, [goalId]),
            returnValue: _i5.Future<_i2.GoalModel>.value(
              _FakeGoalModel_0(this, Invocation.method(#resumeGoal, [goalId])),
            ),
          )
          as _i5.Future<_i2.GoalModel>);

  @override
  _i5.Future<_i2.GoalModel> pauseGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseGoal, [goalId]),
            returnValue: _i5.Future<_i2.GoalModel>.value(
              _FakeGoalModel_0(this, Invocation.method(#pauseGoal, [goalId])),
            ),
          )
          as _i5.Future<_i2.GoalModel>);

  @override
  _i5.Future<_i2.GoalModel> completeGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#completeGoal, [goalId]),
            returnValue: _i5.Future<_i2.GoalModel>.value(
              _FakeGoalModel_0(
                this,
                Invocation.method(#completeGoal, [goalId]),
              ),
            ),
          )
          as _i5.Future<_i2.GoalModel>);
}
