// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/presentation/providers/plan_review_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/plan_review_model.dart' as _i4;
import 'package:myassistant/data/services/plan_review_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PlanReviewService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanReviewService extends _i1.Mock implements _i2.PlanReviewService {
  MockPlanReviewService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PlanReviewModel>> getUserPlanReviews(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPlanReviews, [userId]),
            returnValue: _i3.Future<List<_i4.PlanReviewModel>>.value(
              <_i4.PlanReviewModel>[],
            ),
          )
          as _i3.Future<List<_i4.PlanReviewModel>>);

  @override
  _i3.Future<_i4.PlanReviewModel?> getPlanReview(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanReview, [planId]),
            returnValue: _i3.Future<_i4.PlanReviewModel?>.value(),
          )
          as _i3.Future<_i4.PlanReviewModel?>);

  @override
  _i3.Future<List<_i4.PlanReviewModel>> getPlanReviewsByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanReviewsByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i3.Future<List<_i4.PlanReviewModel>>.value(
              <_i4.PlanReviewModel>[],
            ),
          )
          as _i3.Future<List<_i4.PlanReviewModel>>);

  @override
  _i3.Future<List<_i4.PlanReviewModel>> getGoalPlanReviews(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalPlanReviews, [goalId]),
            returnValue: _i3.Future<List<_i4.PlanReviewModel>>.value(
              <_i4.PlanReviewModel>[],
            ),
          )
          as _i3.Future<List<_i4.PlanReviewModel>>);

  @override
  _i3.Future<Map<String, dynamic>> getUserSummaryStatistics(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserSummaryStatistics, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i4.PlanReviewModel>> getPlansSortedByCompletionRate(
    String? userId, {
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPlansSortedByCompletionRate,
              [userId],
              {#ascending: ascending},
            ),
            returnValue: _i3.Future<List<_i4.PlanReviewModel>>.value(
              <_i4.PlanReviewModel>[],
            ),
          )
          as _i3.Future<List<_i4.PlanReviewModel>>);

  @override
  _i3.Future<List<_i4.PlanReviewModel>> getPlansNeedingAttention(
    String? userId, {
    double? completionRateThreshold = 0.5,
    double? skippedRateThreshold = 0.3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPlansNeedingAttention,
              [userId],
              {
                #completionRateThreshold: completionRateThreshold,
                #skippedRateThreshold: skippedRateThreshold,
              },
            ),
            returnValue: _i3.Future<List<_i4.PlanReviewModel>>.value(
              <_i4.PlanReviewModel>[],
            ),
          )
          as _i3.Future<List<_i4.PlanReviewModel>>);
}
