// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/presentation/providers/plan_state_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/enums/status.dart' as _i11;
import 'package:myassistant/data/models/enums/task_type.dart' as _i9;
import 'package:myassistant/data/models/plan_model.dart' as _i2;
import 'package:myassistant/data/models/task_model.dart' as _i4;
import 'package:myassistant/data/services/plan_management_service.dart' as _i3;
import 'package:myassistant/data/services/task_execution_service.dart' as _i5;
import 'package:myassistant/data/services/task_refresh_service.dart' as _i6;
import 'package:myassistant/domain/repositories/i_plan_repository.dart' as _i7;
import 'package:myassistant/domain/repositories/i_task_repository.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlanModel_0 extends _i1.SmartFake implements _i2.PlanModel {
  _FakePlanModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlanStatistics_1 extends _i1.SmartFake
    implements _i3.PlanStatistics {
  _FakePlanStatistics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskModel_2 extends _i1.SmartFake implements _i4.TaskModel {
  _FakeTaskModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimerSession_3 extends _i1.SmartFake implements _i5.TimerSession {
  _FakeTimerSession_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskCompletionResult_4 extends _i1.SmartFake
    implements _i5.TaskCompletionResult {
  _FakeTaskCompletionResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshResult_5 extends _i1.SmartFake implements _i6.RefreshResult {
  _FakeRefreshResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IPlanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPlanRepository extends _i1.Mock implements _i7.IPlanRepository {
  MockIPlanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.PlanModel> createPlan({
    required String? userId,
    required String? goalId,
    required String? name,
    String? description,
    required DateTime? startDate,
    required DateTime? endDate,
    required _i2.RepeatRule? repeatRule,
    required _i2.TaskConfiguration? taskConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPlan, [], {
              #userId: userId,
              #goalId: goalId,
              #name: name,
              #description: description,
              #startDate: startDate,
              #endDate: endDate,
              #repeatRule: repeatRule,
              #taskConfig: taskConfig,
            }),
            returnValue: _i8.Future<_i2.PlanModel>.value(
              _FakePlanModel_0(
                this,
                Invocation.method(#createPlan, [], {
                  #userId: userId,
                  #goalId: goalId,
                  #name: name,
                  #description: description,
                  #startDate: startDate,
                  #endDate: endDate,
                  #repeatRule: repeatRule,
                  #taskConfig: taskConfig,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.PlanModel>);

  @override
  _i8.Future<_i2.PlanModel?> getPlanById(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanById, [planId]),
            returnValue: _i8.Future<_i2.PlanModel?>.value(),
          )
          as _i8.Future<_i2.PlanModel?>);

  @override
  _i8.Future<List<_i2.PlanModel>> getUserPlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPlans, [userId]),
            returnValue: _i8.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i8.Future<List<_i2.PlanModel>>);

  @override
  _i8.Future<List<_i2.PlanModel>> getGoalPlans(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalPlans, [goalId]),
            returnValue: _i8.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i8.Future<List<_i2.PlanModel>>);

  @override
  _i8.Future<List<_i2.PlanModel>> getActivePlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePlans, [userId]),
            returnValue: _i8.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i8.Future<List<_i2.PlanModel>>);

  @override
  _i8.Future<List<_i2.PlanModel>> getPlansByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i8.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i8.Future<List<_i2.PlanModel>>);

  @override
  _i8.Future<_i2.PlanModel> updatePlan(_i2.PlanModel? plan) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlan, [plan]),
            returnValue: _i8.Future<_i2.PlanModel>.value(
              _FakePlanModel_0(this, Invocation.method(#updatePlan, [plan])),
            ),
          )
          as _i8.Future<_i2.PlanModel>);

  @override
  _i8.Future<bool> deletePlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlan, [planId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> restorePlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#restorePlan, [planId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> isPlanNameExists(String? userId, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#isPlanNameExists, [userId, name]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i2.PlanModel?> getPlanByUserAndName(
    String? userId,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanByUserAndName, [userId, name]),
            returnValue: _i8.Future<_i2.PlanModel?>.value(),
          )
          as _i8.Future<_i2.PlanModel?>);

  @override
  _i8.Future<Map<String, dynamic>> getPlanStatistics(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanStatistics, [planId]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<bool> updatePlanStatistics({
    required String? planId,
    int? totalTaskCount,
    int? completedTaskCount,
    int? skippedTaskCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlanStatistics, [], {
              #planId: planId,
              #totalTaskCount: totalTaskCount,
              #completedTaskCount: completedTaskCount,
              #skippedTaskCount: skippedTaskCount,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<double> calculateCompletionRate(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#calculateCompletionRate, [planId]),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<List<_i2.PlanModel>> getPlansNeedingTaskGeneration(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansNeedingTaskGeneration, [userId]),
            returnValue: _i8.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i8.Future<List<_i2.PlanModel>>);

  @override
  _i8.Future<List<_i2.PlanModel>> searchPlans(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPlans, [userId, query]),
            returnValue: _i8.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i8.Future<List<_i2.PlanModel>>);

  @override
  _i8.Future<List<_i2.PlanModel>> getDeletedPlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedPlans, [userId]),
            returnValue: _i8.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i8.Future<List<_i2.PlanModel>>);

  @override
  _i8.Future<List<_i2.PlanModel>> getPlansEndingSoon(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansEndingSoon, [userId], {#days: days}),
            returnValue: _i8.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i8.Future<List<_i2.PlanModel>>);
}

/// A class which mocks [PlanManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanManagementService extends _i1.Mock
    implements _i3.PlanManagementService {
  MockPlanManagementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.PlanModel> createPlan({
    required String? userId,
    required String? goalId,
    required String? name,
    String? description,
    required DateTime? startDate,
    required DateTime? endDate,
    required _i2.RepeatRule? repeatRule,
    required _i2.TaskConfiguration? taskConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPlan, [], {
              #userId: userId,
              #goalId: goalId,
              #name: name,
              #description: description,
              #startDate: startDate,
              #endDate: endDate,
              #repeatRule: repeatRule,
              #taskConfig: taskConfig,
            }),
            returnValue: _i8.Future<_i2.PlanModel>.value(
              _FakePlanModel_0(
                this,
                Invocation.method(#createPlan, [], {
                  #userId: userId,
                  #goalId: goalId,
                  #name: name,
                  #description: description,
                  #startDate: startDate,
                  #endDate: endDate,
                  #repeatRule: repeatRule,
                  #taskConfig: taskConfig,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.PlanModel>);

  @override
  _i8.Future<_i2.PlanModel> updatePlan({
    required String? planId,
    String? description,
    DateTime? endDate,
    _i2.TaskConfiguration? taskConfig,
    _i2.RepeatRule? repeatRule,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlan, [], {
              #planId: planId,
              #description: description,
              #endDate: endDate,
              #taskConfig: taskConfig,
              #repeatRule: repeatRule,
            }),
            returnValue: _i8.Future<_i2.PlanModel>.value(
              _FakePlanModel_0(
                this,
                Invocation.method(#updatePlan, [], {
                  #planId: planId,
                  #description: description,
                  #endDate: endDate,
                  #taskConfig: taskConfig,
                  #repeatRule: repeatRule,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.PlanModel>);

  @override
  _i8.Future<bool> deletePlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlan, [planId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i3.PlanStatistics> calculatePlanStatistics(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#calculatePlanStatistics, [planId]),
            returnValue: _i8.Future<_i3.PlanStatistics>.value(
              _FakePlanStatistics_1(
                this,
                Invocation.method(#calculatePlanStatistics, [planId]),
              ),
            ),
          )
          as _i8.Future<_i3.PlanStatistics>);

  @override
  _i8.Future<List<String>> getPlanRecommendations(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanRecommendations, [planId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<_i2.PlanModel> extendPlan({
    required String? planId,
    required int? additionalDays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extendPlan, [], {
              #planId: planId,
              #additionalDays: additionalDays,
            }),
            returnValue: _i8.Future<_i2.PlanModel>.value(
              _FakePlanModel_0(
                this,
                Invocation.method(#extendPlan, [], {
                  #planId: planId,
                  #additionalDays: additionalDays,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.PlanModel>);

  @override
  _i8.Future<_i2.PlanModel> clonePlan({
    required String? originalPlanId,
    required String? newGoalId,
    DateTime? newStartDate,
    DateTime? newEndDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clonePlan, [], {
              #originalPlanId: originalPlanId,
              #newGoalId: newGoalId,
              #newStartDate: newStartDate,
              #newEndDate: newEndDate,
            }),
            returnValue: _i8.Future<_i2.PlanModel>.value(
              _FakePlanModel_0(
                this,
                Invocation.method(#clonePlan, [], {
                  #originalPlanId: originalPlanId,
                  #newGoalId: newGoalId,
                  #newStartDate: newStartDate,
                  #newEndDate: newEndDate,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.PlanModel>);

  @override
  _i8.Future<List<_i2.PlanModel>> getPlansByTaskType({
    required String? userId,
    required _i9.TaskType? taskType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansByTaskType, [], {
              #userId: userId,
              #taskType: taskType,
            }),
            returnValue: _i8.Future<List<_i2.PlanModel>>.value(
              <_i2.PlanModel>[],
            ),
          )
          as _i8.Future<List<_i2.PlanModel>>);
}

/// A class which mocks [ITaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRepository extends _i1.Mock implements _i10.ITaskRepository {
  MockITaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.TaskModel> createTask({
    required String? userId,
    required String? planId,
    required String? name,
    String? description,
    required _i2.TaskConfiguration? config,
    required DateTime? windowStartTime,
    required DateTime? windowEndTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {
              #userId: userId,
              #planId: planId,
              #name: name,
              #description: description,
              #config: config,
              #windowStartTime: windowStartTime,
              #windowEndTime: windowEndTime,
            }),
            returnValue: _i8.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#createTask, [], {
                  #userId: userId,
                  #planId: planId,
                  #name: name,
                  #description: description,
                  #config: config,
                  #windowStartTime: windowStartTime,
                  #windowEndTime: windowEndTime,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.TaskModel>);

  @override
  _i8.Future<_i4.TaskModel?> getTaskById(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [taskId]),
            returnValue: _i8.Future<_i4.TaskModel?>.value(),
          )
          as _i8.Future<_i4.TaskModel?>);

  @override
  _i8.Future<List<_i4.TaskModel>> getUserTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTasks, [userId]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> getPlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanTasks, [planId]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> getActiveTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTasks, [userId]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> getTasksInCurrentWindow(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksInCurrentWindow, [userId]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> getTasksByStatus(
    String? userId,
    _i11.TaskStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [userId, status]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> getTasksByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> getTodayTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayTasks, [userId]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> getUpcomingTasks(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingTasks, [userId], {#days: days}),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> getFutureTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFutureTasks, [userId]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> getOverdueTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, [userId]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<_i4.TaskModel> completeTask({
    required String? taskId,
    int? actualDurationMinutes,
    String? evaluationResult,
    String? executionNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [], {
              #taskId: taskId,
              #actualDurationMinutes: actualDurationMinutes,
              #evaluationResult: evaluationResult,
              #executionNote: executionNote,
            }),
            returnValue: _i8.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#completeTask, [], {
                  #taskId: taskId,
                  #actualDurationMinutes: actualDurationMinutes,
                  #evaluationResult: evaluationResult,
                  #executionNote: executionNote,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.TaskModel>);

  @override
  _i8.Future<_i4.TaskModel> skipTask({
    required String? taskId,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#skipTask, [], {
              #taskId: taskId,
              #reason: reason,
            }),
            returnValue: _i8.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#skipTask, [], {
                  #taskId: taskId,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.TaskModel>);

  @override
  _i8.Future<_i4.TaskModel> updateTaskProgress(
    String? taskId,
    int? currentCount, {
    int? actualDurationMinutes,
    String? evaluationResult,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTaskProgress,
              [taskId, currentCount],
              {
                #actualDurationMinutes: actualDurationMinutes,
                #evaluationResult: evaluationResult,
              },
            ),
            returnValue: _i8.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(
                  #updateTaskProgress,
                  [taskId, currentCount],
                  {
                    #actualDurationMinutes: actualDurationMinutes,
                    #evaluationResult: evaluationResult,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i4.TaskModel>);

  @override
  _i8.Future<_i4.TaskModel> updateTaskStatus({
    required String? taskId,
    required _i11.TaskStatus? status,
    bool? clearExecutionData = false,
    bool? clearSkipData = false,
    bool? clearDeletedAt = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [], {
              #taskId: taskId,
              #status: status,
              #clearExecutionData: clearExecutionData,
              #clearSkipData: clearSkipData,
              #clearDeletedAt: clearDeletedAt,
            }),
            returnValue: _i8.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#updateTaskStatus, [], {
                  #taskId: taskId,
                  #status: status,
                  #clearExecutionData: clearExecutionData,
                  #clearSkipData: clearSkipData,
                  #clearDeletedAt: clearDeletedAt,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.TaskModel>);

  @override
  _i8.Future<Map<String, dynamic>> getTaskStatistics(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskStatistics, [userId]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getDailyTaskStatistics(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyTaskStatistics, [userId, date]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<double> getTaskCompletionRate(String? userId, {int? days = 30}) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskCompletionRate, [userId], {#days: days}),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<_i4.TaskModel?> getActivePlanTask(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePlanTask, [planId]),
            returnValue: _i8.Future<_i4.TaskModel?>.value(),
          )
          as _i8.Future<_i4.TaskModel?>);

  @override
  _i8.Future<List<_i4.TaskModel>> batchCreateTasks(
    List<_i4.TaskModel>? tasks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchCreateTasks, [tasks]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<_i4.TaskModel>> searchTasks(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTasks, [userId, query]),
            returnValue: _i8.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i8.Future<List<_i4.TaskModel>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getTaskHistory(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskHistory, [taskId]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<bool> addTaskHistoryEntry({
    required String? taskId,
    required String? userId,
    required String? action,
    String? oldStatus,
    String? newStatus,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskHistoryEntry, [], {
              #taskId: taskId,
              #userId: userId,
              #action: action,
              #oldStatus: oldStatus,
              #newStatus: newStatus,
              #metadata: metadata,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> deletePlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlanTasks, [planId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [TaskExecutionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskExecutionService extends _i1.Mock
    implements _i5.TaskExecutionService {
  MockTaskExecutionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.TimerSession> startTimer({
    required _i4.TaskModel? task,
    dynamic Function(Duration)? onTick,
    dynamic Function()? onComplete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startTimer, [], {
              #task: task,
              #onTick: onTick,
              #onComplete: onComplete,
            }),
            returnValue: _i8.Future<_i5.TimerSession>.value(
              _FakeTimerSession_3(
                this,
                Invocation.method(#startTimer, [], {
                  #task: task,
                  #onTick: onTick,
                  #onComplete: onComplete,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.TimerSession>);

  @override
  _i5.TimerSession? getTimerSession(String? taskId) =>
      (super.noSuchMethod(Invocation.method(#getTimerSession, [taskId]))
          as _i5.TimerSession?);

  @override
  void stopTimer(String? taskId) => super.noSuchMethod(
    Invocation.method(#stopTimer, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i5.TaskCompletionResult> completeTask({
    required _i4.TaskModel? task,
    int? actualDurationMinutes,
    String? evaluationResult,
    String? executionNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [], {
              #task: task,
              #actualDurationMinutes: actualDurationMinutes,
              #evaluationResult: evaluationResult,
              #executionNote: executionNote,
            }),
            returnValue: _i8.Future<_i5.TaskCompletionResult>.value(
              _FakeTaskCompletionResult_4(
                this,
                Invocation.method(#completeTask, [], {
                  #task: task,
                  #actualDurationMinutes: actualDurationMinutes,
                  #evaluationResult: evaluationResult,
                  #executionNote: executionNote,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.TaskCompletionResult>);

  @override
  _i8.Future<_i4.TaskModel> skipTask({
    required _i4.TaskModel? task,
    String? skipReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#skipTask, [], {
              #task: task,
              #skipReason: skipReason,
            }),
            returnValue: _i8.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#skipTask, [], {
                  #task: task,
                  #skipReason: skipReason,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.TaskModel>);

  @override
  _i8.Future<_i4.TaskModel> incrementCount(
    _i4.TaskModel? task, {
    int? actualDurationMinutes,
    String? evaluationResult,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #incrementCount,
              [task],
              {
                #actualDurationMinutes: actualDurationMinutes,
                #evaluationResult: evaluationResult,
              },
            ),
            returnValue: _i8.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(
                  #incrementCount,
                  [task],
                  {
                    #actualDurationMinutes: actualDurationMinutes,
                    #evaluationResult: evaluationResult,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i4.TaskModel>);

  @override
  _i8.Future<_i4.TaskModel> decrementCount(_i4.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#decrementCount, [task]),
            returnValue: _i8.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#decrementCount, [task]),
              ),
            ),
          )
          as _i8.Future<_i4.TaskModel>);

  @override
  _i8.Future<_i4.TaskModel?> reExecuteTask(_i4.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#reExecuteTask, [task]),
            returnValue: _i8.Future<_i4.TaskModel?>.value(),
          )
          as _i8.Future<_i4.TaskModel?>);

  @override
  Map<String, _i5.TimerSession> getActiveSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSessions, []),
            returnValue: <String, _i5.TimerSession>{},
          )
          as Map<String, _i5.TimerSession>);

  @override
  void pauseAllTimers() => super.noSuchMethod(
    Invocation.method(#pauseAllTimers, []),
    returnValueForMissingStub: null,
  );

  @override
  void resumeAllTimers() => super.noSuchMethod(
    Invocation.method(#resumeAllTimers, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TaskRefreshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRefreshService extends _i1.Mock
    implements _i6.TaskRefreshService {
  MockTaskRefreshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.RefreshResult> refreshAllTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAllTasks, [userId]),
            returnValue: _i8.Future<_i6.RefreshResult>.value(
              _FakeRefreshResult_5(
                this,
                Invocation.method(#refreshAllTasks, [userId]),
              ),
            ),
          )
          as _i8.Future<_i6.RefreshResult>);

  @override
  void startPeriodicRefresh({
    required String? userId,
    Duration? interval = const Duration(hours: 1),
    dynamic Function(_i6.RefreshResult)? onRefresh,
  }) => super.noSuchMethod(
    Invocation.method(#startPeriodicRefresh, [], {
      #userId: userId,
      #interval: interval,
      #onRefresh: onRefresh,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void stopPeriodicRefresh() => super.noSuchMethod(
    Invocation.method(#stopPeriodicRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> scheduleRefreshAt(List<DateTime>? times, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleRefreshAt, [times, userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.RefreshResult> refreshOnResume(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshOnResume, [userId]),
            returnValue: _i8.Future<_i6.RefreshResult>.value(
              _FakeRefreshResult_5(
                this,
                Invocation.method(#refreshOnResume, [userId]),
              ),
            ),
          )
          as _i8.Future<_i6.RefreshResult>);

  @override
  _i8.Future<_i4.TaskModel?> refreshPlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshPlanTasks, [planId]),
            returnValue: _i8.Future<_i4.TaskModel?>.value(),
          )
          as _i8.Future<_i4.TaskModel?>);

  @override
  _i8.Future<int> cleanupOldTasks({
    required String? userId,
    int? daysOld = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldTasks, [], {
              #userId: userId,
              #daysOld: daysOld,
            }),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
