// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/presentation/providers/task_list_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/enums/status.dart' as _i8;
import 'package:myassistant/data/models/plan_model.dart' as _i7;
import 'package:myassistant/data/models/task_model.dart' as _i2;
import 'package:myassistant/data/services/task_execution_service.dart' as _i3;
import 'package:myassistant/data/services/task_refresh_service.dart' as _i4;
import 'package:myassistant/domain/repositories/i_task_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimerSession_1 extends _i1.SmartFake implements _i3.TimerSession {
  _FakeTimerSession_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskCompletionResult_2 extends _i1.SmartFake
    implements _i3.TaskCompletionResult {
  _FakeTaskCompletionResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshResult_3 extends _i1.SmartFake implements _i4.RefreshResult {
  _FakeRefreshResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ITaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRepository extends _i1.Mock implements _i5.ITaskRepository {
  MockITaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.TaskModel> createTask({
    required String? userId,
    required String? planId,
    required String? name,
    String? description,
    required _i7.TaskConfiguration? config,
    required DateTime? windowStartTime,
    required DateTime? windowEndTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {
              #userId: userId,
              #planId: planId,
              #name: name,
              #description: description,
              #config: config,
              #windowStartTime: windowStartTime,
              #windowEndTime: windowEndTime,
            }),
            returnValue: _i6.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#createTask, [], {
                  #userId: userId,
                  #planId: planId,
                  #name: name,
                  #description: description,
                  #config: config,
                  #windowStartTime: windowStartTime,
                  #windowEndTime: windowEndTime,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<_i2.TaskModel?> getTaskById(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [taskId]),
            returnValue: _i6.Future<_i2.TaskModel?>.value(),
          )
          as _i6.Future<_i2.TaskModel?>);

  @override
  _i6.Future<List<_i2.TaskModel>> getUserTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTasks, [userId]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> getPlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanTasks, [planId]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> getActiveTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTasks, [userId]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> getTasksInCurrentWindow(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksInCurrentWindow, [userId]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> getTasksByStatus(
    String? userId,
    _i8.TaskStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [userId, status]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> getTasksByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> getTodayTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayTasks, [userId]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> getUpcomingTasks(
    String? userId, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingTasks, [userId], {#days: days}),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> getFutureTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFutureTasks, [userId]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> getOverdueTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, [userId]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<_i2.TaskModel> completeTask({
    required String? taskId,
    int? actualDurationMinutes,
    String? evaluationResult,
    String? executionNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [], {
              #taskId: taskId,
              #actualDurationMinutes: actualDurationMinutes,
              #evaluationResult: evaluationResult,
              #executionNote: executionNote,
            }),
            returnValue: _i6.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#completeTask, [], {
                  #taskId: taskId,
                  #actualDurationMinutes: actualDurationMinutes,
                  #evaluationResult: evaluationResult,
                  #executionNote: executionNote,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<_i2.TaskModel> skipTask({
    required String? taskId,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#skipTask, [], {
              #taskId: taskId,
              #reason: reason,
            }),
            returnValue: _i6.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#skipTask, [], {
                  #taskId: taskId,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<_i2.TaskModel> updateTaskProgress(
    String? taskId,
    int? currentCount, {
    int? actualDurationMinutes,
    String? evaluationResult,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTaskProgress,
              [taskId, currentCount],
              {
                #actualDurationMinutes: actualDurationMinutes,
                #evaluationResult: evaluationResult,
              },
            ),
            returnValue: _i6.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(
                  #updateTaskProgress,
                  [taskId, currentCount],
                  {
                    #actualDurationMinutes: actualDurationMinutes,
                    #evaluationResult: evaluationResult,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<_i2.TaskModel> updateTaskStatus({
    required String? taskId,
    required _i8.TaskStatus? status,
    bool? clearExecutionData = false,
    bool? clearSkipData = false,
    bool? clearDeletedAt = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [], {
              #taskId: taskId,
              #status: status,
              #clearExecutionData: clearExecutionData,
              #clearSkipData: clearSkipData,
              #clearDeletedAt: clearDeletedAt,
            }),
            returnValue: _i6.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#updateTaskStatus, [], {
                  #taskId: taskId,
                  #status: status,
                  #clearExecutionData: clearExecutionData,
                  #clearSkipData: clearSkipData,
                  #clearDeletedAt: clearDeletedAt,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<Map<String, dynamic>> getTaskStatistics(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskStatistics, [userId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getDailyTaskStatistics(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyTaskStatistics, [userId, date]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<double> getTaskCompletionRate(String? userId, {int? days = 30}) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskCompletionRate, [userId], {#days: days}),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<_i2.TaskModel?> getActivePlanTask(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePlanTask, [planId]),
            returnValue: _i6.Future<_i2.TaskModel?>.value(),
          )
          as _i6.Future<_i2.TaskModel?>);

  @override
  _i6.Future<List<_i2.TaskModel>> batchCreateTasks(
    List<_i2.TaskModel>? tasks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchCreateTasks, [tasks]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<_i2.TaskModel>> searchTasks(String? userId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTasks, [userId, query]),
            returnValue: _i6.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getTaskHistory(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskHistory, [taskId]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<bool> addTaskHistoryEntry({
    required String? taskId,
    required String? userId,
    required String? action,
    String? oldStatus,
    String? newStatus,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskHistoryEntry, [], {
              #taskId: taskId,
              #userId: userId,
              #action: action,
              #oldStatus: oldStatus,
              #newStatus: newStatus,
              #metadata: metadata,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> deletePlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlanTasks, [planId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [TaskExecutionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskExecutionService extends _i1.Mock
    implements _i3.TaskExecutionService {
  MockTaskExecutionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.TimerSession> startTimer({
    required _i2.TaskModel? task,
    dynamic Function(Duration)? onTick,
    dynamic Function()? onComplete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startTimer, [], {
              #task: task,
              #onTick: onTick,
              #onComplete: onComplete,
            }),
            returnValue: _i6.Future<_i3.TimerSession>.value(
              _FakeTimerSession_1(
                this,
                Invocation.method(#startTimer, [], {
                  #task: task,
                  #onTick: onTick,
                  #onComplete: onComplete,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.TimerSession>);

  @override
  _i3.TimerSession? getTimerSession(String? taskId) =>
      (super.noSuchMethod(Invocation.method(#getTimerSession, [taskId]))
          as _i3.TimerSession?);

  @override
  void stopTimer(String? taskId) => super.noSuchMethod(
    Invocation.method(#stopTimer, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i3.TaskCompletionResult> completeTask({
    required _i2.TaskModel? task,
    int? actualDurationMinutes,
    String? evaluationResult,
    String? executionNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [], {
              #task: task,
              #actualDurationMinutes: actualDurationMinutes,
              #evaluationResult: evaluationResult,
              #executionNote: executionNote,
            }),
            returnValue: _i6.Future<_i3.TaskCompletionResult>.value(
              _FakeTaskCompletionResult_2(
                this,
                Invocation.method(#completeTask, [], {
                  #task: task,
                  #actualDurationMinutes: actualDurationMinutes,
                  #evaluationResult: evaluationResult,
                  #executionNote: executionNote,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.TaskCompletionResult>);

  @override
  _i6.Future<_i2.TaskModel> skipTask({
    required _i2.TaskModel? task,
    String? skipReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#skipTask, [], {
              #task: task,
              #skipReason: skipReason,
            }),
            returnValue: _i6.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#skipTask, [], {
                  #task: task,
                  #skipReason: skipReason,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<_i2.TaskModel> incrementCount(
    _i2.TaskModel? task, {
    int? actualDurationMinutes,
    String? evaluationResult,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #incrementCount,
              [task],
              {
                #actualDurationMinutes: actualDurationMinutes,
                #evaluationResult: evaluationResult,
              },
            ),
            returnValue: _i6.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(
                  #incrementCount,
                  [task],
                  {
                    #actualDurationMinutes: actualDurationMinutes,
                    #evaluationResult: evaluationResult,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<_i2.TaskModel> decrementCount(_i2.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#decrementCount, [task]),
            returnValue: _i6.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#decrementCount, [task]),
              ),
            ),
          )
          as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<_i2.TaskModel?> reExecuteTask(_i2.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#reExecuteTask, [task]),
            returnValue: _i6.Future<_i2.TaskModel?>.value(),
          )
          as _i6.Future<_i2.TaskModel?>);

  @override
  Map<String, _i3.TimerSession> getActiveSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSessions, []),
            returnValue: <String, _i3.TimerSession>{},
          )
          as Map<String, _i3.TimerSession>);

  @override
  void pauseAllTimers() => super.noSuchMethod(
    Invocation.method(#pauseAllTimers, []),
    returnValueForMissingStub: null,
  );

  @override
  void resumeAllTimers() => super.noSuchMethod(
    Invocation.method(#resumeAllTimers, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TaskRefreshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRefreshService extends _i1.Mock
    implements _i4.TaskRefreshService {
  MockTaskRefreshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.RefreshResult> refreshAllTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAllTasks, [userId]),
            returnValue: _i6.Future<_i4.RefreshResult>.value(
              _FakeRefreshResult_3(
                this,
                Invocation.method(#refreshAllTasks, [userId]),
              ),
            ),
          )
          as _i6.Future<_i4.RefreshResult>);

  @override
  void startPeriodicRefresh({
    required String? userId,
    Duration? interval = const Duration(hours: 1),
    dynamic Function(_i4.RefreshResult)? onRefresh,
  }) => super.noSuchMethod(
    Invocation.method(#startPeriodicRefresh, [], {
      #userId: userId,
      #interval: interval,
      #onRefresh: onRefresh,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void stopPeriodicRefresh() => super.noSuchMethod(
    Invocation.method(#stopPeriodicRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> scheduleRefreshAt(List<DateTime>? times, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleRefreshAt, [times, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.RefreshResult> refreshOnResume(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshOnResume, [userId]),
            returnValue: _i6.Future<_i4.RefreshResult>.value(
              _FakeRefreshResult_3(
                this,
                Invocation.method(#refreshOnResume, [userId]),
              ),
            ),
          )
          as _i6.Future<_i4.RefreshResult>);

  @override
  _i6.Future<_i2.TaskModel?> refreshPlanTasks(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshPlanTasks, [planId]),
            returnValue: _i6.Future<_i2.TaskModel?>.value(),
          )
          as _i6.Future<_i2.TaskModel?>);

  @override
  _i6.Future<int> cleanupOldTasks({
    required String? userId,
    int? daysOld = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldTasks, [], {
              #userId: userId,
              #daysOld: daysOld,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
