// Mocks generated by Mockito 5.4.6 from annotations
// in myassistant/test/presentation/widgets/edit_plan_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:myassistant/data/models/plan_model.dart' as _i5;
import 'package:myassistant/data/services/plan_management_service.dart' as _i6;
import 'package:myassistant/presentation/providers/plan_state_provider.dart'
    as _i2;
import 'package:state_notifier/state_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlanListState_0 extends _i1.SmartFake implements _i2.PlanListState {
  _FakePlanListState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlanListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanListNotifier extends _i1.Mock implements _i2.PlanListNotifier {
  MockPlanListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i3.Stream<_i2.PlanListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i3.Stream<_i2.PlanListState>.empty(),
          )
          as _i3.Stream<_i2.PlanListState>);

  @override
  _i2.PlanListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePlanListState_0(this, Invocation.getter(#state)),
          )
          as _i2.PlanListState);

  @override
  _i2.PlanListState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakePlanListState_0(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i2.PlanListState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  set onError(_i4.ErrorListener? _onError) => super.noSuchMethod(
    Invocation.setter(#onError, _onError),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i2.PlanListState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> loadPlans() =>
      (super.noSuchMethod(
            Invocation.method(#loadPlans, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadGoalPlans(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#loadGoalPlans, [goalId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.PlanModel?> createPlan({
    required String? goalId,
    required String? name,
    String? description,
    required DateTime? startDate,
    required DateTime? endDate,
    required _i5.RepeatRule? repeatRule,
    required _i5.TaskConfiguration? taskConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPlan, [], {
              #goalId: goalId,
              #name: name,
              #description: description,
              #startDate: startDate,
              #endDate: endDate,
              #repeatRule: repeatRule,
              #taskConfig: taskConfig,
            }),
            returnValue: _i3.Future<_i5.PlanModel?>.value(),
          )
          as _i3.Future<_i5.PlanModel?>);

  @override
  _i3.Future<_i5.PlanModel?> updatePlan({
    required String? planId,
    String? description,
    DateTime? endDate,
    _i5.TaskConfiguration? taskConfig,
    _i5.RepeatRule? repeatRule,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlan, [], {
              #planId: planId,
              #description: description,
              #endDate: endDate,
              #taskConfig: taskConfig,
              #repeatRule: repeatRule,
            }),
            returnValue: _i3.Future<_i5.PlanModel?>.value(),
          )
          as _i3.Future<_i5.PlanModel?>);

  @override
  _i3.Future<bool> deletePlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlan, [planId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i5.PlanModel?> extendPlan({
    required String? planId,
    required int? additionalDays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extendPlan, [], {
              #planId: planId,
              #additionalDays: additionalDays,
            }),
            returnValue: _i3.Future<_i5.PlanModel?>.value(),
          )
          as _i3.Future<_i5.PlanModel?>);

  @override
  _i3.Future<_i6.PlanStatistics?> getPlanStatistics(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanStatistics, [planId]),
            returnValue: _i3.Future<_i6.PlanStatistics?>.value(),
          )
          as _i3.Future<_i6.PlanStatistics?>);

  @override
  _i3.Future<List<String>> getPlanRecommendations(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanRecommendations, [planId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  bool updateShouldNotify(_i2.PlanListState? old, _i2.PlanListState? current) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.RemoveListener addListener(
    _i7.Listener<_i2.PlanListState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
          )
          as _i4.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
